/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  Ralru
 * Created: Nov 11, 2024
 */


CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone CHAR(10),
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    role VARCHAR(20)
);

CREATE TABLE trainer(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    trainershift VARCHAR(50),
    CONSTRAINT fk_traineruser FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE admins (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    CONSTRAINT fk_adminuser FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE member (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    membership VARCHAR(50),
    CONSTRAINT fk_memberuser FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE service (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    amount NUMBER NOT NULL
);

CREATE TABLE classes (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    trainer_id NUMBER NOT NULL,
    day VARCHAR(10),
    time VARCHAR(10),
    capacity VARCHAR(10), 
    Description VARCHAR(100),
    CONSTRAINT fktrainer FOREIGN KEY (trainer_id) REFERENCES trainer(id)
);

CREATE TABLE feedback (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    trainer_id NUMBER NOT NULL,
    feedbackMessage VARCHAR(100) NOT NULL,
    CONSTRAINT fkmemberid FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE CASCADE,
    CONSTRAINT fktraineiId FOREIGN KEY (trainer_id) REFERENCES trainer(id) ON DELETE CASCADE
);

CREATE TABLE member_service (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    service_id NUMBER NOT NULL,
    CONSTRAINT fkmember FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE CASCADE,
    CONSTRAINT fkservice FOREIGN KEY (service_id) REFERENCES service(id) ON DELETE CASCADE
);
CREATE TABLE member_classes(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    classes_id NUMBER NOT NULL,
    CONSTRAINT usermember_id FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE CASCADE,
    CONSTRAINT fk_classes FOREIGN KEY (classes_id) REFERENCES classes(id) ON DELETE CASCADE
)
 